from telegram import Update, ReplyKeyboardMarkup, InlineKeyboardMarkup, InlineKeyboardButton
from telegram.ext import ApplicationBuilder, CommandHandler, MessageHandler, CallbackQueryHandler, ContextTypes, filters
import os

# Asosiy menyu
main_menu_keyboard = [
    ["Tahlillar haqida", "Qon topshirish qoidalari"],
    ["Bioximik tahlillar", "Klinik tahlillar"],
    ["IXLA va IFA farqi", "Biz bilan bog'lanish"],
    ["Tahlil natijalari", "Taklif va shikoyatlar"],
    ["Kitob (testlar haqida)", "Foydalanuvchi qo'shish"],
    ["Organizmda qanday o'zgarish?"]
]
main_menu = ReplyKeyboardMarkup(main_menu_keyboard, resize_keyboard=True)

# Gormonlar ro'yxati
hormone_buttons = [
    "TSH", "FT4", "FT3", "Prolaktin", "Estradiol", "Testosteron", "LH", "FSH", "Progesteron", "AMH",
    "Insulin", "C_peptid", "ACTH", "Kortizol", "PTH", "Vitamin_D", "HCG", "DHEA_S", "IGF_1", "Aldosteron",
    "Renin", "Androstenedion", "Adiponektin", "Ghrelin", "Leptin", "Beta-hCG", "Calcitonin", "Somatotropin",
    "Proinsulin", "SHBG", "17-OH Progesteron", "Anti-TPO", "Anti-Tg", "FSH/LH nisbati", "Insulin Resistence",
    "Melatonin", "Parathormon", "Free Estriol", "Inhibin B", "Mullerian Inhibiting Substance", "Oxytocin",
    "Relaxin", "Vasopressin", "Kisspeptin", "Adrenalin", "Noradrenalin", "Thyroglobulin", "Catecholamines",
    "Plazma Metanefrin"
]
hormone_keyboard = [[InlineKeyboardButton(text, callback_data=text)] for text in hormone_buttons]
hormone_menu = InlineKeyboardMarkup(hormone_keyboard)

# Har bir gormon haqida ma'lumot (Hozircha TSH va FT4, keyin barchasini to‘ldirib beraman)
hormone_info = {
    "TSH": "🔬 TSH (Qalqonsimon bez stimulyator gormoni)\n➔ Norma: 0.27 – 4.2 mIU/L\n📈 Oshganda: Gipotiroidizm\n📉 Kamayganda: Gipertiroidizm\n⚡ Belgilar: Holsizlik, sovuqqa sezuvchanlik, vazn ortishi.\n🕒 Tekshirish: Holsizlik va qalqonsimon bez kasalliklari belgilari.",
    "FT4": "🔬 FT4 (Erkin Tiroksin)\n➔ Norma: 0.93 – 1.7 ng/dL\n📈 Oshganda: Gipertiroidizm\n📉 Kamayganda: Gipotiroidizm\n⚡ Belgilar: Yurak urishining tezlashishi, vazn kamayishi.\n🕒 Tekshirish: Qalqonsimon bez faoliyati shubhasida."
}

# /start komandasi
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "Assalomu alaykum! Kushon Medical Servis laboratoriyasi botiga xush kelibsiz!\n\nMenyudan kerakli bo'limni tanlang:",
        reply_markup=main_menu
    )

# Menyudagi tugmalarni ishlovchi
async def handle_menu_selection(update: Update, context: ContextTypes.DEFAULT_TYPE):
    text = update.message.text

    if text == "Tahlillar haqida":
        await update.message.reply_text("Gormonlar ro'yxati:", reply_markup=hormone_menu)
    elif text == "Qon topshirish qoidalari":
        await update.message.reply_text("Qon topshirishdan oldin 8-12 soat och qolish tavsiya etiladi. Ertalab soat 7-10 oralig'ida.")
    elif text == "Bioximik tahlillar":
        await update.message.reply_text("Bioximik tahlillar: Glukoza, Kreatinin, AST, ALT, Bilirubin va boshqalar.")
    elif text == "Klinik tahlillar":
        await update.message.reply_text("Klinik tahlillar: Umumiy qon tahlili va siydik tahlili haqida.")
    elif text == "IXLA va IFA farqi":
        await update.message.reply_text("IXLA zamonaviy va aniq, IFA esa nisbatan eski texnologiya.")
    elif text == "Biz bilan bog'lanish":
        await update.message.reply_text("Manzil: Kosonsoy tumani, Poliklinika yonida.\nTelefon: +998907417222\nInstagram: @akmal.jon7222\nTelegram: @Akmaljon_lab\nEmail: Akmaljon.19@bk.ru")
    elif text == "Tahlil natijalari":
        await update.message.reply_text("ID raqamingizni yuboring.")
    elif text == "Taklif va shikoyatlar":
        await update.message.reply_text("Taklif va shikoyatlaringizni yozib yuboring.")
    elif text == "Kitob (testlar haqida)":
        await update.message.reply_text("📚 Testlar haqida kitob pullik! Narxi: 45 000 so'm.\nAdmin bilan bog'laning: @Akmaljon_lab")
    elif text == "Foydalanuvchi qo'shish":
        await update.message.reply_text("✅ Ro'yxatdan o'tdingiz! Botni do'stlaringizga tavsiya qiling.")
    elif text == "Organizmda qanday o'zgarish?":
        await update.message.reply_text("📋 Organizmingizdagi o'zgarish yoki shikoyatni yozing, biz sizga mos tahlillarni tavsiya qilamiz.")
    else:
        await update.message.reply_text("Iltimos, menyudan tanlang.")

# Inline tugmalar ishlovchi
async def handle_callback(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    await query.answer()
    info = hormone_info.get(query.data)
    if info:
        await query.edit_message_text(info)
    else:
        await query.edit_message_text("Bu test haqida ma'lumot hali tayyor emas.")

# Main funksiyasi
def main():
    token = os.getenv("TOKEN")
    if not token:
        raise RuntimeError("Bot token topilmadi. Iltimos, .env faylga TOKEN kiriting.")
    app = ApplicationBuilder().token(token).build()

    app.add_handler(CommandHandler("start", start))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_menu_selection))
    app.add_handler(CallbackQueryHandler(handle_callback))

    print("✅ Bot ishga tushdi...")
    app.run_polling()
# Har bir gormon haqida to'liq ma'lumot
hormone_info = {
    "TSH": "🔬 TSH (Qalqonsimon bez stimulyator gormoni)\n"
           "➔ Norma: 0.27 – 4.2 mIU/L\n\n"
           "📈 Oshganda:\n"
           "- Gipotiroidizm (qalqonsimon bez faoliyatining pasayishi)\n"
           "- Hashimoto tireoiditi (autoimmun kasallik)\n"
           "- Qalqonsimon bezni jarrohlik yoki radiatsiya bilan olib tashlash\n\n"
           "📉 Kamayganda:\n"
           "- Gipertiroidizm (qalqonsimon bez faoliyatining ortishi)\n"
           "- Graves kasalligi (autoimmun gipertiroidizm)\n"
           "- Nodular toksik zob\n\n"
           "⚡ Organizmdagi belgilar:\n"
           "- Holsizlik va tez charchash\n"
           "- Sovuqqa sezuvchanlik\n",
    "FT4": "🔬 FT4 (Erkin tiroksin)\n"
       "➔ Norma: 0.93 – 1.7 ng/dL\n\n"
       "📈 Oshganda:\n"
       "- Gipertiroidizm (qalqonsimon bez faoliyatining ortishi)\n"
       "- Graves kasalligi\n"
       "- Toksik zob (qalqonsimon bezdagi o'smalar)\n\n"
       "📉 Kamayganda:\n"
       "- Gipotiroidizm (qalqonsimon bez faoliyatining pasayishi)\n"
       "- Hashimoto tireoiditi\n"
       "- Qalqonsimon bez shikastlanishi yoki yallig‘lanishi\n\n"
       "⚡ Organizmdagi belgilar:\n"
       "- Yurak urishining tezlashishi\n"
       "- Vazn kamayishi\n"
       "- Asabiylik, xavotirlik\n"
       "- Tana haroratining ko‘tarilishi\n"
       "- Terlashning ortishi\n"
       "- Holsizlik va mushak zaifligi\n"
       "- Ko‘zlar oldida shish (ekzoftalmiya)\n\n"
       "⏰ Qachon tekshirish kerak:\n"
       "- Tez charchash va asabiylik\n"
       "- Odatdan tashqari vazn kamayishi\n"
       "- Yurak urishining tezlashishi\n"
       "- Qalqonsimon bez kasalligi shubhasida\n"
       "- Homiladorlikda qalqonsimon bez nazorati uchun",
"FT3": "🔬 FT3 (Erkin triyodtironin)\n"
       "➔ Norma: 2.0 – 4.4 pg/mL\n\n"
       "📈 Oshganda:\n"
       "- Gipertiroidizm (qalqonsimon bez faoliyatining ortishi)\n"
       "- Graves kasalligi\n"
       "- Toksik adenoma (qalqonsimon bez o‘smasi)\n\n"
       "📉 Kamayganda:\n"
       "- Gipotiroidizm (qalqonsimon bez faoliyatining pasayishi)\n"
       "- Hashimoto tireoiditi\n"
       "- Og‘ir umumiy kasallik sindromi (sepsis, yurak yetishmovchiligi)\n\n"
       "⚡ Organizmdagi belgilar:\n"
       "- Tez asabiylashish, bezovtalik\n"
       "- Terlashning kuchayishi\n"
       "- Yurak urishining tezlashishi (taxikardiya)\n"
       "- Vazn kamayishi\n"
       "- Tana haroratining ko‘tarilishi\n"
       "- Mushak zaifligi\n"
       "- Uyqusizlik\n\n"
       "⏰ Qachon tekshirish kerak:\n"
       "- Yurak urishining tezlashishi\n"
       "- Asabiylik va ruhiy o‘zgarishlar\n"
       -" Tez-tez issiqlik sezish va terlash\n"
       "- Odatdan tashqari vazn kamayishi\n"
       "- Qalqonsimon bez kasalliklari shubhasida"
           "- Vazn ortishi yoki kamayishi\n"
           "- Ruhiy tushkunlik\n"
           "- Yurak urishining buzilishi (sekin yoki tez)\n"
           "- Tana haroratining pasayishi yoki ko‘tarilishi\n"
           "- Teri qurishi va soch to‘kilishi\n\n"
           "⏰ Qachon tekshirish kerak:\n"
           "- Charchoq va kuchsizlik\n"
           "- Qorinning shishishi yoki vazn ortishi\n"
           "- Sovuqqa sezuvchanlik kuchayganda\n"
           "- Hayz siklining buzilishi\n"
           "- Homiladorlikda qalqonsimon bezni nazorat qilishda"
"Prolaktin": "🔬 Prolaktin (Sut bezlari va jinsiy faoliyat gormoni)\n",
             "➔ Norma:\n"
             "- Ayollar: 4.8 – 23.3 ng/mL\n"
             "- Erkaklar: 4.0 – 15.2 ng/mL\n\n"
             "📈 Oshganda:\n"
             "- Prolaktinoma (prolaktin ishlab chiqaruvchi o'sma)\n"
             "- Gipotiroidizm\n"
             "- Stress yoki ko‘p jismoniy mashqlar\n"
             "- Homiladorlik va laktatsiya\n"
             "- Ba'zi dorilar (antipsixotiklar, antidepressantlar)\n\n"
             "📉 Kamayganda:\n"
             "- Gipopituitarizm (gipofiz bezining faoliyat pasayishi)\n"
             "- Qattiq stress yoki gipofiz zararlanishi\n\n"
             "⚡ Organizmdagi belgilar:\n"
             "- Ayollarda hayz ko‘rishning buzilishi (oligomenoreya yoki amenoreya)\n"
             "- Sut ajralib chiqishi (galaktoreya)\n"
             "- Bepushtlik\n"
             "- Erkaklarda jinsiy zaiflik va libidoning pasayishi\n"
             "- Ko‘kraklarda shish yoki og‘riq\n\n"
             "⏰ Qachon tekshirish kerak:\n"
             "- Ayollarda hayz buzilishi va bepushtlik holatida\n"
             "- Erkaklarda jinsiy zaiflik va bepushtlikda\n"
             "- Sut chiqishi yoki ko‘krak bezlarida o‘zgarishlarda\n"
             "- Shubhali gipofiz kasalliklarida",
"Estradiol": "🔬 Estradiol (E2) - Asosiy ayollar jinsiy gormoni\n"
             "➔ Norma:\n"
             "- Ayollar (fertil davrda): 70 – 530 pg/mL\n"
             "- Ayollar (menopauzada): < 50 pg/mL\n"
             "- Erkaklar: 10 – 50 pg/mL\n\n"
             "📈 Oshganda:\n"
             "- Yumurtalik (ovarial) o'smalari\n"
             "- Homiladorlik\n"
             "- Estrogen gormon terapiyasi\n"
             "- Jigar kasalliklari\n\n"
             "📉 Kamayganda:\n"
             "- Menopauza (hayz tugashi)\n"
             "- Gipogonadizm (jinsiy bezlarning yetishmovchiligi)\n"
             "- Anoreksiya\n"
             "- Surunkali kasalliklar va og‘ir stress\n\n"
             "⚡ Organizmdagi belgilar:\n"
             "- Ayollarda hayz ko‘rishning buzilishi yoki hayz to‘xtashi\n"
             "- Behosdan bepushtlik\n"
             "- Teri qurishi va suyaklarning zaiflashishi\n"
             "- Qattiq kayfiyat o‘zgarishlari va depressiya\n"
             "- Erkaklarda ko‘krak bezi kattalashishi (ginekomastiya)\n\n"
             "⏰ Qachon tekshirish kerak:\n"
             "- Hayz buzilishlari va bepushtlikda\n"
             "- Menopauza simptomlari paydo bo‘lganda\n"
             "- Erkaklarda ginekomastiya yoki reproduktiv buzilishlarda\n"
             "- Homiladorlikni kuzatishda",
"Testosteron": "🔬 Testosteron (Erkaklik gormoni, ayollarda ham oz miqdorda mavjud)\n"
               "➔ Norma:\n"
               "- Erkaklar: 300 – 1000 ng/dL\n"
               "- Ayollar: 15 – 70 ng/dL\n\n"
               "📈 Oshganda:\n"
               "- Polikistik tuxumdon sindromi (ayollarda)\n"
               "- Androgen ishlab chiqaruvchi o'smalar\n"
               "- Dopingi (sun'iy testosteron qabul qilish)\n\n"
               "📉 Kamayganda:\n"
               "- Gipogonadizm (erkaklarda jinsiy bezlar yetishmovchiligi)\n"
               "- Keksa yoshdagi pasayish (andropauza)\n"
               "- Stress va surunkali kasalliklar\n\n"
               "⚡ Organizmdagi belgilar:\n"
               "- Erkaklarda jinsiy zaiflik, libidoning pasayishi\n"
               "- Mushak massasining kamayishi\n"
               "- Depressiya va ruhiy zaiflik\n"
               "- Ayollarda erkaklarcha belgilarning kuchayishi (soch o‘sishi, ovoz qattiqlashuvi)\n\n"
               "⏰ Qachon tekshirish kerak:\n"
               "- Erkaklarda jinsiy zaiflik va bepushtlikda\n"
               "- Ayollarda gormon buzilishlari yoki polikistik tuxumdon sindromi shubhasida",
"LH": "🔬 LH (Luteinizatsiya qiluvchi gormon)\n"
      "➔ Norma:\n"
      "- Ayollar (ovulyasiya oldi): 10 – 90 IU/L\n"
      "- Ayollar (folikulyar faza): 2 – 15 IU/L\n"
      "- Erkaklar: 1.8 – 8.6 IU/L\n\n"
      "📈 Oshganda:\n"
      "- Ovulyasiya davrida (normal)\n"
      "- Polikistik tuxumdon sindromi (ayollarda)\n"
      "- Gipogonadotropik gipogonadizm\n\n"
      "📉 Kamayganda:\n"
      "- Gipopituitarizm (gipofiz bezining zaiflashishi)\n"
      "- Stress, anoreksiya\n"
      "- Gormonal muvozanat buzilishi\n\n"
      "⚡ Organizmdagi belgilar:\n"
      "- Hayz tsikli buzilishi\n"
      "- Ovulyasiya yo‘qligi (ayollarda)\n"
      "- Bepushtlik\n"
      "- Erkaklarda testosteron yetishmovchiligi\n\n"
      "⏰ Qachon tekshirish kerak:\n"
      "- Bepushtlik va hayz buzilishlari shubhasida\n"
      "- Gormon buzilishi belgilarida\n"
      "- Erkaklarda jinsiy rivojlanish buzilishida",
"FSH": "🔬 FSH (Follikulani stimullovchi gormon)\n"
       "➔ Norma:\n"
       "- Ayollar (folikulyar faza): 3 – 12 IU/L\n"
       "- Ayollar (ovulyasiya oldi): 4 – 25 IU/L\n"
       "- Ayollar (menopauza): 25 – 135 IU/L\n"
       "- Erkaklar: 1.5 – 12.4 IU/L\n\n"
       "📈 Oshganda:\n"
       "- Menopauza\n"
       "- Gonad (jinsiy bez) yetishmovchiligi\n"
       "- Polikistik tuxumdon sindromi\n\n"
       "📉 Kamayganda:\n"
       "- Gipopituitarizm\n"
       "- Gipotalamus yoki gipofiz shikastlanishi\n"
       "- Stress va semizlik\n\n"
       "⚡ Organizmdagi belgilar:\n"
       "- Bepushtlik\n"
       "- Ayollarda hayz siklining buzilishi\n"
       "- Ovulyatsiya yo‘qligi\n"
       "- Erkaklarda spermatozoid ishlab chiqarish pasayishi\n\n"
       "⏰ Qachon tekshirish kerak:\n"
       "- Bepushtlik shikoyatlarida\n"
       "- Hayz tsikli buzilganda\n"
       "- Gonadlar faoliyatini baholashda",
"Progesteron": "🔬 Progesteron (Homiladorlik va hayz siklini nazorat qiluvchi gormon)\n"
               "➔ Norma:\n"
               "- Ayollar (luteal faza): 5 – 20 ng/mL\n"
               "- Ayollar (folikulyar faza): 0.2 – 1.5 ng/mL\n"
               "- Homiladorlikda: 11 – 90 ng/mL\n\n"
               "📈 Oshganda:\n"
               "- Homiladorlik (normal holat)\n"
               "- Tuxumdon kistalari\n"
               "- Adrenal giperplaziya (buyrak usti bezining o‘sishi)\n\n"
               "📉 Kamayganda:\n"
               "- Luteal faza yetishmovchiligi\n"
               "- Tuxumdon disfunksiyasi\n"
               "- Homiladorlikda homila xavfi\n\n"
               "⚡ Organizmdagi belgilar:\n"
               "- Homiladorlikda erta tushish xavfi\n"
               "- Hayz ko‘rish oldidan og‘riq va noqulaylik\n"
               "- Bepushtlik\n"
               "- Ovulyasiya buzilishi\n\n"
               "⏰ Qachon tekshirish kerak:\n"
               "- Bepushtlikda\n"
               "- Ovulyasiyani tekshirishda\n"
               "- Homiladorlikni nazorat qilishda\n"
               "- Hayz buzilishi yoki gormon yetishmovchiligi belgilarida",
"AMH": "🔬 AMH (Anti-Mullerian Hormone)\n"
       "➔ Norma:\n"
       "- Ayollar (fertil davrda): 1.0 – 4.0 ng/mL\n"
       "- Ayollar (menopauza): < 0.5 ng/mL\n\n"
       "📈 Oshganda:\n"
       "- Polikistik tuxumdon sindromi (PCOS)\n"
       "- Ovarial (tuxumdon) giperplaziya\n\n"
       "📉 Kamayganda:\n"
       "- Tuxumdon zaxirasi kamaygan\n"
       "- Menopauza yoki perimenopauza\n"
       "- Tuxumdonlar shikastlanishi\n\n"
       "⚡ Organizmdagi belgilar:\n"
       "- Bepushtlik\n"
       "- Ovulyasiyaning buzilishi\n"
       "- Hayz siklining buzilishi\n\n"
       "⏰ Qachon tekshirish kerak:\n"
       "- Bepushtlik diagnostikasi\n"
       "- Tuxumdon zaxirasini baholash\n"
       "- Sun'iy urug'lantirish (IVF) rejalashtirishdan oldin",
"Insulin": "🔬 Insulin (Qonda glyukoza miqdorini nazorat qiluvchi gormon)\n"
            "➔ Norma:\n"
            "- Och qoringa: 2.6 – 24.9 uIU/mL\n\n"
            "📈 Oshganda:\n"
            "- 2-tip qandli diabet\n"
            "- Insulinoma (insulin ishlab chiqaruvchi o'sma)\n"
            "- Semizlik\n"
            "- Polikistik tuxumdon sindromi (PCOS)\n\n"
            "📉 Kamayganda:\n"
            "- 1-tip qandli diabet\n"
            "- Og‘ir pankreatit (oshqozon osti bezi yallig‘lanishi)\n\n"
            "⚡ Organizmdagi belgilar:\n"
            "- Shakar darajasining o‘zgarishi\n"
            - Hipoglikemiya (shakar pasayishi) simptomlari: bosh aylanishi, terlash, hushyorlikning pasayishi\n"
            "- Tez och qolish, charchoq\n"
\n"
            "⏰ Qachon tekshirish kerak:\n"
            "- Qandli diabet diagnostikasida\n"
            "- Insulin qarshiligi shubhasida (semizlik, PCOS)\n"
            "- Glyukoza darajasini nazorat qilishda",
"C_peptid": "🔬 C-peptid (Insulin ishlab chiqarilishini ko'rsatkich gormoni)\n"
             "➔ Norma:\n"
             "- Och qoringa: 0.5 – 2.0 ng/mL\n\n"
             "📈 Oshganda:\n"
             "- 2-tip qandli diabet\n"
             "- Insulinoma (oshqozon osti bezining o‘smasi)\n"
             "- Insulin qarshiligi (semizlik, PCOS)\n\n"
             "📉 Kamayganda:\n"
             "- 1-tip qandli diabet\n"
             "- Pankreatit (oshqozon osti bezi yallig‘lanishi)\n\n"
             "⚡ Organizmdagi belgilar:\n"
             "- Tez-tez chanqash va och qolish\n"
             "- Hipoglikemiya yoki giperglikemiya belgilarining kuchayishi\n"
             "- Charchoq va vazn yo‘qotish\n\n"
             "⏰ Qachon tekshirish kerak:\n"
             "- Qandli diabet turi va holatini aniqlashda\n"
             "- Insulin ishlab chiqarilishini baholashda",
"ACTH": "🔬 ACTH (Adrenokortikotropik gormon)\n"
         "➔ Norma:\n"
         "- 10 – 60 pg/mL\n\n"
         "📈 Oshganda:\n"
         "- Kuşing kasalligi (gipofizdagi ACTH o‘smasi)\n"
         "- Stress va depressiya\n"
         "- Ektopik ACTH ishlab chiqaruvchi o‘sma\n\n"
         "📉 Kamayganda:\n"
         "- Adrenal yetishmovchiligi (Addison kasalligi)\n"
         "- Sekundar gipokortitsizm\n\n"
         "⚡ Organizmdagi belgilar:\n"
         "- Doimiy charchoq\n"
         "- Qon bosimining pasayishi\n"
         "- Terining qorayishi (giperpigmentatsiya)\n"
         "- Shakar va tuz darajasining pasayishi\n\n"
         "⏰ Qachon tekshirish kerak:\n"
         "- Qorachilik, kuchsizlanish va charchoq belgilarida\n"
         "- Endokrin kasalliklar shubhasida",
"Kortizol": "🔬 Kortizol (Stress gormoni)\n"
             "➔ Norma:\n"
             "- Ertalab (08:00): 6.2 – 19.4 µg/dL\n"
             "- Kechqurun (20:00): 2.3 – 11.9 µg/dL\n\n"
             "📈 Oshganda:\n"
             "- Kuşing sindromi\n"
             "- Stress, semizlik\n"
             "- Gormon ishlab chiqaruvchi o‘sma\n\n"
             "📉 Kamayganda:\n"
             "- Addison kasalligi (buyrak usti bezining yetishmovchiligi)\n"
             "- Sekundar gipokortitsizm\n\n"
             "⚡ Organizmdagi belgilar:\n"
             "- Qon bosimining o‘zgarishi\n"
             "- Tez-tez charchoq va zaiflik\n"
             "- Vazn ortishi (ayniqsa qorin sohasida)\n"
             "- Depressiya va ruhiy buzilishlar\n\n"
             "⏰ Qachon tekshirish kerak:\n"
             "- Surunkali stress va charchoqda\n"
             "- Endokrin kasalliklar shubhasida\n"
             "- Shakar va tuz darajasi buzilgan hollarda",
"PTH": "🔬 PTH (Paratiroid gormoni, suyak va kaltsiy almashinuvi nazoratchisi)\n"
        "➔ Norma:\n"
        "- 10 – 65 pg/mL\n\n"
        "📈 Oshganda:\n"
        - Giperparatiroidizm\n"
        "- Buyrak yetishmovchiligi\n"
        "- D vitamini yetishmovchiligi\n\n"
        "📉 Kamayganda:\n"
        "- Gipoparatiroidizm\n"
        "- Qattiq suyak kasalliklari\n"
        "- D vitaminining haddan tashqari ortishi\n\n"
        "⚡ Organizmdagi belgilar:\n"
        "- Suyaklar zaiflashishi va sinishi\n"
        "- Mushaklarda spazmlar va kuchsizlik\n"
        "- Qon kaltsiy darajasining o‘zgarishi\n\n"
        "⏰ Qachon tekshirish kerak:\n"
        "- Suyak sinishlariga moyillikda\n"
        "- Buyrak kasalliklari bilan kasallanganda\n"
        "- Qon kaltsiy darajasining pasayishi yoki oshishi aniqlanganda",
"Vitamin_D": "🔬 Vitamin D (D vitamini, suyak va immun tizimi uchun muhim)\n"
              "➔ Norma:\n"
              "- 30 – 100 ng/mL\n\n"
              "📈 Oshganda:\n"
              "- Vitamin D giperdozaligi (kam uchraydi)\n"
              "- Kaltsiy darajasining ortishi\n\n"
              "📉 Kamayganda:\n"
              "- D vitamini yetishmovchiligi\n"
              "- Raxit (bolalarda)\n"
              "- Osteomalatsiya va osteoporoz (suyaklarning zaiflashishi)\n\n"
              "⚡ Organizmdagi belgilar:\n"
              "- Suyak og‘rig‘i va zaifligi\n"
              "- Tez-tez shamollash va immunitet pasayishi\n"
              "- Depressiya va charchoq\n"
              "- Mushaklarning kuchsizlanishi\n\n"
              "⏰ Qachon tekshirish kerak:\n"
              "- Suyak zaifligi va sinish hollari\n"
              "- Surunkali charchoq va immunitet pasayganida\n"
              "- Bolalarda suyak rivojlanishida buzilishlar bo'lsa",
"HCG": "🔬 HCG (Homiladorlik gormoni)\n"
        "➔ Norma:\n"
        "- Homiladorliksiz: < 5 mIU/mL\n"
        "- Homiladorlik 1-hafta: 5 – 50 mIU/mL\n"
        "- Homiladorlik davomida: Minglab mIU/mL gacha\n\n"
        "📈 Oshganda:\n"
        "- Homiladorlik\n"
        "- Ko‘p homilali homiladorlik (egizaklar)\n"
        "- Xorionik karsinoma yoki boshqa onkologik kasalliklar\n\n"
        "📉 Kamayganda:\n"
        "- Homiladorlikning to‘xtashi (abort xavfi)\n"
        "- Homilada rivojlanish muammolari\n\n"
        "⚡ Organizmdagi belgilar:\n"
        "- Homiladorlik simptomlari (ko‘ngil aynishi, ko‘krak sezuvchanligi)\n"
        "- Rivojlanmayotgan homiladorlikda belgilarning kamayishi\n\n"
        "⏰ Qachon tekshirish kerak:\n"
        "- Homiladorlikni tasdiqlash uchun\n"
        "- Homiladorlikning rivojlanishini nazorat qilish uchun\n"
        "- Ektopik homiladorlikni tashxislashda",
"DHEA_S": "🔬 DHEA-S (Dehidroepiandrosteron sulfat, gormon prekursori)\n"
           "➔ Norma:\n"
           "- Ayollar: 35 – 430 µg/dL\n"
           "- Erkaklar: 80 – 560 µg/dL\n\n"
           "📈 Oshganda:\n"
           "- Adrenal giperplaziya (buyrak usti bezining faoliyati oshishi)\n"
           "- Androgen ishlab chiqaruvchi o‘sma\n"
           "- Polikistik tuxumdon sindromi (PCOS)\n\n"
           "📉 Kamayganda:\n"
           "- Buyrak usti bezining yetishmovchiligi (Addison kasalligi)\n"
           "- Gormon ishlab chiqarishining pasayishi\n"
           "- Keksa yoshdagi tabiiy kamayish\n\n"
           "⚡ Organizmdagi belgilar:\n"
           "- Ayollarda erkaklarcha belgilar (soch o‘sishi, akne)\n"
           "- Bepushtlik\n"
           "- Energiya yetishmovchiligi va kuchsizlik\n\n"
           "⏰ Qachon tekshirish kerak:\n"
           "- Gormon buzilishlari shubhasida\n"
           "- Bepushtlik va erkaklarcha belgilar bo‘lsa\n"
           "- Buyrak usti bezining faoliyatini baholash uchun",
"IGF_1": "🔬 IGF-1 (Insulin-like Growth Factor 1, o‘sish va tiklanish gormoni)\n"
          "➔ Norma:\n"
          "- Yoshga va jinsga qarab: 100 – 600 ng/mL (bolalar va o‘smirlar uchun yuqoriroq)\n\n"
          "📈 Oshganda:\n"
          "- Akromegaliya (o‘sish gormoni ortiqligi)\n"
          "- Gigantizm (bolalarda haddan tashqari o‘sish)\n\n"
          "📉 Kamayganda:\n"
          "- O‘sish gormoni yetishmovchiligi\n"
          "- Surunkali kasalliklar (qandli diabet, jigar kasalliklari)\n"
          "- Keksa yoshdagi tabiiy kamayish\n\n"
          "⚡ Organizmdagi belgilar:\n"
          "- Bolalarda o‘sishning sekinlashuvi\n"
          "- Kattalarda suyak zaifligi va mushak massasining kamayishi\n"
          "- Surunkali charchoq va zaiflik\n\n"
          "⏰ Qachon tekshirish kerak:\n"
          "- O‘sishning sekinlashuvi yoki haddan tashqari o‘sishda\n"
          "- Akromegaliya shubhasida\n"
          "- Surunkali kasalliklar nazoratida",
"Aldosteron": "🔬 Aldosteron (Qon bosimi va suyuqlik muvozanatini boshqaruvchi gormon)\n"
               "➔ Norma:\n"
               "- Yotgan holatda: 3 – 16 ng/dL\n"
               "- Tik holatda: 7 – 30 ng/dL\n\n"
               "📈 Oshganda:\n"
               "- Birlamchi aldosteronizm (Konn sindromi)\n"
               "- Qon bosimining oshishi (gipertenziya)\n"
               "- Buyrak arteriyalarining torayishi\n\n"
               "📉 Kamayganda:\n"
               "- Adrenal yetishmovchiligi (Addison kasalligi)\n"
               "- Gormon ishlab chiqaruvchi o‘sma yo‘qligi\n\n"
               "⚡ Organizmdagi belgilar:\n"
               "- Qon bosimi o‘zgarishi\n"
               "- Suvsizlanish va elektrolit buzilishlar (kaltsiy, natriy, kaliy)\n"
               "- Charchoq va zaiflik\n\n"
               "⏰ Qachon tekshirish kerak:\n"
               "- Qon bosimi baland va gormon buzilishi shubhasida\n"
               "- Elektrolitlar (kaliy) darajasi o‘zgarib ketganda",
"Renin": "🔬 Renin (Qon bosimi va suyuqlik muvozanatini tartibga soluvchi ferment)\n"
          "➔ Norma:\n"
          "- 0.5 – 4.0 ng/mL/soat (holatga qarab o‘zgaradi)\n\n"
          "📈 Oshganda:\n"
          "- Buyrak arteriyalarining torayishi\n"
          "- Gipopituitarizm\n"
          "- Qon bosimi past bo‘lganda\n\n"
          "📉 Kamayganda:\n"
          "- Birlamchi aldosteronizm (Konn sindromi)\n"
          "- Buyrak usti bezlari kasalliklari\n"
          "- Gipertenziya (ba'zi hollarda)\n\n"
          "⚡ Organizmdagi belgilar:\n"
          "- Qon bosimining notekisligi\n"
          "- Suvsizlanish, charchoq\n"
          "- Elektrolitlar muvozanatining buzilishi\n\n"
          "⏰ Qachon tekshirish kerak:\n"
          "- Gormon buzilishi bilan bog‘liq gipertenziya shubhasida\n"
          "- Buyrak kasalliklari va suyuqlik muvozanati buzilganda",
"Androstenedion": "🔬 Androstenedion (Erkak va ayol gormonlarining ajralish prekursori)\n"
                   "➔ Norma:\n"
                   "- Ayollar: 0.3 – 3.5 ng/mL\n"
                   "- Erkaklar: 0.6 – 3.1 ng/mL\n\n"
                   "📈 Oshganda:\n"
                   "- Polikistik tuxumdon sindromi (PCOS)\n"
                   "- Adrenal giperplaziya\n"
                   "- Androgen ishlab chiqaruvchi o‘sma\n\n"
                   "📉 Kamayganda:\n"
                   "- Buyrak usti bezining faoliyat yetishmovchiligi\n"
                   "- Gonadlarning disfunksiyasi\n\n"
                   "⚡ Organizmdagi belgilar:\n"
                   "- Ayollarda erkaklarcha belgilarning kuchayishi (soch o‘sishi, akne)\n"
                   "- Hayz tsikli buzilishi\n"
                   "- Bepushtlik\n\n"
                   "⏰ Qachon tekshirish kerak:\n"
                   "- Gormon buzilishlari va erkaklarcha belgilar paydo bo‘lsa\n"
                   "- Bepushtlikda\n"
                   "- PCOS diagnostikasida",
"Adiponektin": "🔬 Adiponektin (Yog‘ to‘qimalaridan ajraladigan va metabolizmni boshqaradigan gormon)\n"
                "➔ Norma:\n"
                "- Ayollar: 5 – 30 µg/mL\n"
                "- Erkaklar: 3 – 20 µg/mL\n\n"
                "📈 Oshganda:\n"
                "- Ozg‘inlik (normal)\n"
                "- Yurak-qon tomir sog‘lig‘i yaxshilanishi\n\n"
                "📉 Kamayganda:\n"
                "- Semizlik\n"
                "- 2-tip qandli diabet\n"
                "- Insulin qarshiligi\n"
                "- Yurak-qon tomir kasalliklari\n\n"
                "⚡ Organizmdagi belgilar:\n"
                "- Qandli diabet rivojlanishi\n"
                "- Semizlik va metabolik sindrom belgilari\n"
                "- Qon lipidlarining buzilishi\n\n"
                "⏰ Qachon tekshirish kerak:\n"
                "- Semizlikda va qandli diabet shubhasida\n"
                "- Yurak-qon tomir xavfini baholashda\n"
                "- Insulin qarshiligi mavjud bo‘lsa",
"Ghrelin": "🔬 Ghrelin (Ochlik va ishtaha gormoni)\n"
            "➔ Norma:\n"
            "- Och qoringa: 100 – 1200 pg/mL\n\n"
            "📈 Oshganda:\n"
            "- Och qolish (fasting)\n"
            "- Anoreksiya nervoza\n"
            "- Ozg‘inlik va ovqat yetishmovchiligi\n\n"
            "📉 Kamayganda:\n"
            "- Semizlik\n"
            "- Surunkali ovqatlanish ortiqligi\n\n"
            "⚡ Organizmdagi belgilar:\n"
            "- Tez och qolish\n"
            "- Ishtahaning kuchayishi yoki kamayishi\n"
            "- Vazn o‘zgarishi\n\n"
            "⏰ Qachon tekshirish kerak:\n"
            "- Ishtaha buzilishlari bo‘lsa\n"
            "- Semizlik yoki anoreksiya shubhasida\n"
            "- Metabolik buzilishlar baholanishida",
"Leptin": "🔬 Leptin (To‘qlik hissi va yog‘ metabolizmini tartibga soluvchi gormon)\n"
           "➔ Norma:\n"
           "- Ayollar: 4 – 25 ng/mL\n"
           "- Erkaklar: 2 – 10 ng/mL\n\n"
           "📈 Oshganda:\n"
           "- Semizlik\n"
           "- Leptin qarshiligi (to‘qlik signali pasayishi)\n\n"
           "📉 Kamayganda:\n"
           "- Anoreksiya\n"
           "- Ozg‘inlik\n"
           "- Ovqat yetishmovchiligi\n\n"
           "⚡ Organizmdagi belgilar:\n"
           "- Haddan tashqari semirish yoki ozib ketish\n"
           "- To‘qlik hissining buzilishi\n"
           "- Gormon disbalansi\n\n"
           "⏰ Qachon tekshirish kerak:\n"
           "- Semizlik yoki anoreksiya aniqlanganda\n"
           "- Metabolik sindrom va gormon buzilishi shubhasida",
"Beta_hCG": "🔬 Beta-hCG (Homiladorlik gormoni, maxsus subunit)\n"
             "➔ Norma:\n"
             "- Homiladorliksiz: < 5 mIU/mL\n"
             "- Homiladorlikning 1-haftasida: 5 – 50 mIU/mL\n"
             "- Keyingi haftalarda: Minglab mIU/mL gacha\n\n"
             "📈 Oshganda:\n"
             "- Homiladorlik (normal)\n"
             "- Ko‘p homilali homiladorlik (egizaklar)\n"
             "- Xorionik karsinoma (onkologik kasallik)\n\n"
             "📉 Kamayganda:\n"
             "- Homiladorlikning rivojlanmasligi\n"
             "- Homila nobud bo‘lishi\n\n"
             "⚡ Organizmdagi belgilar:\n"
             "- Homiladorlik simptomlari (ko‘ngil aynishi, ko‘krak sezuvchanligi)\n"
             "- Rivojlanmayotgan homiladorlikda simptomlarning kamayishi\n\n"
             "⏰ Qachon tekshirish kerak:\n"
             "- Homiladorlikni tasdiqlash uchun\n"
             "- Homiladorlikning rivojlanishini kuzatishda\n"
             "- Ektopik homiladorlikda shubha bo‘lsa",
"Calcitonin": "🔬 Calcitonin (Qon kaltsiy darajasini tartibga soluvchi gormon)\n"
               "➔ Norma:\n"
               "- Ayollar: < 5 pg/mL\n"
               "- Erkaklar: < 8.5 pg/mL\n\n"
               "📈 Oshganda:\n"
               "- Medullary tireoid rak (qalqonsimon bez o‘smalari)\n"
               "- Buyrak kasalliklari\n"
               "- Xronik pankreatit\n\n"
               "📉 Kamayganda:\n"
               "- Kaltsiy almashinuvining buzilishi\n"
               "- Gormon ishlab chiqarishining pasayishi\n\n"
               "⚡ Organizmdagi belgilar:\n"
               "- Qalqonsimon bez o‘sma belgilariga o‘xshash simptomlar\n"
               "- Suv-elektrolit muvozanatining buzilishi\n"
               "- Suyak zaifligi\n\n"
               "⏰ Qachon tekshirish kerak:\n"
               "- Qalqonsimon bezda o‘sma aniqlanganda\n"
               "- Kaltsiy va suyak muammolari bo‘lsa\n"
               "- Medullary tireoid rak diagnostikasi va nazoratida",
"Somatotropin": "🔬 Somatotropin (O‘sish gormoni, GH)\n"
                 "➔ Norma:\n"
                 "- Kattalar: 0 – 5 ng/mL\n"
                 "- Bolalar: 0 – 20 ng/mL\n\n"
                 "📈 Oshganda:\n"
                 "- Akromegaliya (kattalarda)\n"
                 "- Gigantizm (bolalarda)\n"
                 "- Gormon ishlab chiqaruvchi o‘sma\n\n"
                 "📉 Kamayganda:\n"
                 "- O‘sish gormoni yetishmovchiligi\n"
                 "- Gipopituitarizm\n\n"
                 "⚡ Organizmdagi belgilar:\n"
                 "- Bolalarda o‘sishning sekinlashuvi\n"
                 "- Suyak va mushak massasining kamayishi\n"
                 "- Charchoq va kuchsizlik\n\n"
                 "⏰ Qachon tekshirish kerak:\n"
                 "- O‘sish buzilishlari yoki suyak zaifligi holatida\n"
                 "- Gigantizm yoki akromegaliya shubhasida",
"Proinsulin": "🔬 Proinsulin (Insulin prekursori, qandli diabet belgisi)\n"
               "➔ Norma:\n"
               "- 3 – 20 pmol/L\n\n"
               "📈 Oshganda:\n"
               "- 2-tip qandli diabet\n"
               "- Insulinoma\n"
               "- Insulin qarshiligi\n\n"
               "📉 Kamayganda:\n"
               "- 1-tip qandli diabet\n"
               "- Pankreatik beta hujayralarining yetishmovchiligi\n\n"
               "⚡ Organizmdagi belgilar:\n"
               "- Qonda shakar darajasining o‘zgarishi\n"
               "- Hipoglikemiya yoki giperglikemiya simptomlari\n"
               "- Tez-tez chanqash, ko‘p siydik ajratish\n\n"
               "⏰ Qachon tekshirish kerak:\n"
               "- Qandli diabet diagnostikasida\n"
               "- Beta-hujayra faoliyatini baholashda",
"SHBG": "🔬 SHBG (Sex Hormone Binding Globulin, jinsiy gormonlarni bog‘lovchi globulin)\n"
         "➔ Norma:\n"
         "- Ayollar: 18 – 144 nmol/L\n"
         "- Erkaklar: 10 – 80 nmol/L\n\n"
         "📈 Oshganda:\n"
         "- Gipoandrogenizm (jinsiy gormonlar kamayishi)\n"
         "- Gipertireoz (qalqonsimon bez faoliyati oshishi)\n\n"
         "📉 Kamayganda:\n"
         "- Gipotireoz\n"
         "- Semizlik\n"
         "- Insulin qarshiligi\n\n"
         "⚡ Organizmdagi belgilar:\n"
         "- Libidoning o‘zgarishi\n"
         "- Gormon disbalansi\n"
         "- Reproduktiv muammolar\n\n"
         "⏰ Qachon tekshirish kerak:\n"
         "- Jinsiy gormonlar buzilishida\n"
         "- Bepushtlik va metabolik sindrom shubhasida",
"17_OH_Progesteron": "🔬 17-OH Progesteron (Steroid gormon prekursori)\n"
                      "➔ Norma:\n"
                      "- Folikulyar faza: 0.2 – 1.2 ng/mL\n"
                      "- Luteal faza: 1 – 4.5 ng/mL\n"
                      "- Homiladorlikda: 2 – 5 ng/mL\n\n"
                      "📈 Oshganda:\n"
                      "- Tug‘ma adrenal giperplaziya\n"
                      "- Polikistik tuxumdon sindromi (PCOS)\n\n"
                      "📉 Kamayganda:\n"
                      "- Buyrak usti bezining yetishmovchiligi\n"
                      "- Tuxumdon faoliyatining pasayishi\n\n"
                      "⚡ Organizmdagi belgilar:\n"
                      "- Bepushtlik\n"
                      "- Hayz siklining buzilishi\n"
                      "- Maskulinizatsiya belgilari (ayollarda erkaklarcha belgilar)\n\n"
                      "⏰ Qachon tekshirish kerak:\n"
                      "- Tug‘ma adrenal giperplaziya shubhasida\n"
                      "- Gormon buzilishi va reproduktiv muammolar bo‘lsa",
"Anti_TPO": "🔬 Anti-TPO (Qalqonsimon bezga qarshi antitelalar)\n"
             "➔ Norma:\n"
             "- < 35 IU/mL\n\n"
             "📈 Oshganda:\n"
             "- Hashimoto tireoiditi\n"
             "- Graves kasalligi\n"
             "- Autoimmun tireoidit\n\n"
             "📉 Kamayganda:\n"
             "- Normal holat (sog‘lom)\n\n"
             "⚡ Organizmdagi belgilar:\n"
             "- Qalqonsimon bez funksiyasining buzilishi\n"
             "- Sovuqqa sezuvchanlik, charchoq\n"
             "- Hayz tsiklining buzilishi\n\n"
             "⏰ Qachon tekshirish kerak:\n"
             "- Qalqonsimon bez kasalliklari shubhasida\n"
             "- Autoimmun kasalliklar tashxisida",
             
"Anti_Tg": "🔬 Anti-Tg (Tireoglobulinga qarshi antitelalar)\n"
            "➔ Norma:\n"
            "- < 115 IU/mL\n\n"
            "📈 Oshganda:\n"
            "- Hashimoto tireoiditi\n"
            "- Graves kasalligi\n"
            "- Qalqonsimon bez shishlari\n\n"
            "📉 Kamayganda:\n"
            "- Normal holat\n\n"
            "⚡ Organizmdagi belgilar:\n"
            "- Qalqonsimon bezdagi shish va o‘sma belgilar\n"
            "- Gormon disbalansi\n\n"
            "⏰ Qachon tekshirish kerak:\n"
            "- Qalqonsimon bez faoliyatini tekshirishda\n"
            "- Autoimmun kasalliklar shubhasida",
            
"FSH_LH_nisbati": "🔬 FSH/LH nisbati (Reproduktiv gormonlar balansi)\n"
                   "➔ Norma:\n"
                   "- Ayollarda: 1 – 2\n\n"
                   "📈 FSH/LH nisbati o‘zgarishi:\n"
                   "- PCOS (LH ko‘proq)\n"
                   "- Menopauza (FSH ko‘proq)\n\n"
                   "⚡ Organizmdagi belgilar:\n"
                   "- Ovulyasiya buzilishi\n"
                   "- Hayz tsikli buzilishi\n"
                   "- Bepushtlik\n\n"
                   "⏰ Qachon tekshirish kerak:\n"
                   "- Bepushtlikda\n"
                   "- Hayz tsikli muammolarida\n"
                   "- Gormon balansi baholashda",
                   
"Insulin_Resistance": "🔬 Insulin qarshiligi (Insulin Resistance)\n"
                       "➔ Norma:\n"
                       "- HOMA-IR indeksi: < 2.5\n\n"
                       "📈 Oshganda:\n"
                       "- Semizlik\n"
                       "- 2-tip qandli diabet\n"
                       "- Metabolik sindrom\n\n"
                       "⚡ Organizmdagi belgilar:\n"
                       "- Qorin atrofida yog‘ to‘planishi\n"
                       "- Tez och qolish, charchoq\n"
                       "- Glyukoza darajasining oshishi\n\n"
                       "⏰ Qachon tekshirish kerak:\n"
                       "- Semizlikda\n"
                       "- Qandli diabet shubhasida\n"
                       "- Metabolik sindrom aniqlashda",
"Melatonin": "🔬 Melatonin (Uyqu va biologik ritmlarni tartibga soluvchi gormon)\n"
              "➔ Norma:\n"
              "- Tunda: 10 – 80 pg/mL\n"
              "- Kunduzgi vaqt: < 10 pg/mL\n\n"
              "📈 Oshganda:\n"
              "- Biologik soatning buzilishi\n"
              "- Uyqusizlik\n"
              "- Stress yoki melatonin terapiyasi\n\n"
              "📉 Kamayganda:\n"
              "- Uyqusizlik\n"
              "- Depressiya va surunkali stress\n\n"
              "⚡ Organizmdagi belgilar:\n"
              "- Uyqu buzilishi\n"
              "- Biologik ritm o‘zgarishi\n"
              "- Ruhiy tushkunlik\n\n"
              "⏰ Qachon tekshirish kerak:\n"
              "- Uyqusizlik va depressiya belgilarida\n"
              "- Biologik ritmlarning buzilishi holatida",
              
"Parathormon": "🔬 Parathormon (Qon kaltsiy va fosfor muvozanatini boshqaruvchi gormon)\n"
                "➔ Norma:\n"
                "- 10 – 65 pg/mL\n\n"
                "📈 Oshganda:\n"
                "- Birlamchi giperparatiroidizm\n"
                "- Buyrak yetishmovchiligi\n"
                "- D vitamini yetishmovchiligi\n\n"
                "📉 Kamayganda:\n"
                "- Gipoparatiroidizm\n"
                "- Qattiq suyak kasalliklari\n\n"
                "⚡ Organizmdagi belgilar:\n"
                "- Suyak sinuvchanligi\n"
                "- Qon kaltsiy darajasining o‘zgarishi\n"
                "- Mushak spazmlari\n\n"
                "⏰ Qachon tekshirish kerak:\n"
                "- Kaltsiy va suyak muammolarida\n"
                "- Buyrak kasalliklari va vitamin D yetishmovchiligi shubhasida",
                
"Free_Estriol": "🔬 Free Estriol (Erkin Estriol, homiladorlik gormoni)\n"
                 "➔ Norma:\n"
                 "- Homiladorlik davomida: haftalarga qarab o‘zgaradi\n\n"
                 "📈 Oshganda:\n"
                 "- Ko‘p homilali homiladorlik\n"
                 "- Homiladorlikning normal rivojlanishi\n\n"
                 "📉 Kamayganda:\n"
                 "- Homiladorlik rivojlanishining pasayishi\n"
                 "- Xromosomal anomaliyalar (Down sindromi)\n\n"
                 "⚡ Organizmdagi belgilar:\n"
                 "- Homiladorlikda rivojlanish muammolari\n"
                 "- Xavfli belgilar (tushish xavfi)\n\n"
                 "⏰ Qachon tekshirish kerak:\n"
                 "- Homiladorlikda skrining tekshiruvlarida\n"
                 "- Xomila rivojlanishini baholash uchun",
                 
"Inhibin_B": "🔬 Inhibin B (Reproduktiv tizim faoliyatini nazorat qiluvchi gormon)\n"
              "➔ Norma:\n"
              "- Ayollar (fertil faza): 45 – 300 pg/mL\n"
              "- Erkaklar: 42 – 392 pg/mL\n\n"
              "📈 Oshganda:\n"
              "- Sertoli hujayralari faoliyati oshishi\n"
              "- Ayrim tuxumdon o‘sma turlari\n\n"
              "📉 Kamayganda:\n"
              "- Tuxumdon va sperma yetilmasligi\n"
              "- Bepushtlik\n"
              "- Menopauza\n\n"
              "⚡ Organizmdagi belgilar:\n"
              "- Fertilitet (homilador bo‘lish) muammolari\n"
              "- Hayz tsikli buzilishi\n\n"
              "⏰ Qachon tekshirish kerak:\n"
              "- Bepushtlik diagnostikasida\n"
              "- Reproduktiv salomatlikni baholashda",
"Mullerian_Inhibiting_Substance": "🔬 Mullerian Inhibiting Substance (MIS, AMH deb ham ataladi, jinsiy rivojlanishni boshqaruvchi gormon)\n"
                                   "➔ Norma:\n"
                                   "- Ayollar (fertil faza): 1.0 – 4.0 ng/mL\n"
                                   "- Erkaklar (chaqaloqlarda): Yuqori darajada\n\n"
                                   "📈 Oshganda:\n"
                                   "- Sertoli hujayralari faoliyatining oshishi\n"
                                   "- Tuxumdon va moyak o‘sma turlari\n\n"
                                   "📉 Kamayganda:\n"
                                   "- Tuxumdon zaxirasining kamayishi\n"
                                   "- Bepushtlik\n"
                                   "- Menopauza\n\n"
                                   "⚡ Organizmdagi belgilar:\n"
                                   "- Fertilitet muammolari\n"
                                   "- Homilador bo‘lolmaslik\n"
                                   "- Hayz tsikli buzilishi\n\n"
                                   "⏰ Qachon tekshirish kerak:\n"
                                   "- Bepushtlikda\n"
                                   "- Reproduktiv salomatlikni baholashda",

"Oxytocin": "🔬 Oxytocin (Mehr-muhabbat va ijtimoiy aloqalarni boshqaruvchi gormon)\n"
             "➔ Norma:\n"
             "- O‘zgaruvchan, test laboratoriya metodikasiga qarab baholanadi\n\n"
             "📈 Oshganda:\n"
             "- Tug‘ruq jarayoni va ko‘krak suti chiqarishda\n"
             "- Ijtimoiy aloqalarning kuchayishi\n\n"
             "📉 Kamayganda:\n"
             "- Depressiya\n"
             "- Autizm spektr buzilishlari\n\n"
             "⚡ Organizmdagi belgilar:\n"
             "- Ruhiy tushkunlik\n"
             "- Ijtimoiy izolyatsiya\n"
             "- Emotsional sovuqlik\n\n"
             "⏰ Qachon tekshirish kerak:\n"
             "- Ruhiy va ijtimoiy buzilishlar aniqlanganda\n"
             "- Tug‘ruq va laktatsiyani baholashda",

"Relaxin": "🔬 Relaxin (Homiladorlik davrida suyak va paylarning yumshashini ta’minlovchi gormon)\n"
            "➔ Norma:\n"
            "- Homiladorlikda: Yuqori\n"
            "- Homiladorsiz: Past\n\n"
            "📈 Oshganda:\n"
            "- Homiladorlik (normal holat)\n\n"
            "📉 Kamayganda:\n"
            "- Homiladorlikni yo‘qotish xavfi\n"
            "- Tug‘ruqdagi muammolar\n\n"
            "⚡ Organizmdagi belgilar:\n"
            "- Tug‘ruqdagi suyak va paylarning yetarlicha tayyorlanmasligi\n"
            "- Tushish xavfi\n\n"
            "⏰ Qachon tekshirish kerak:\n"
            "- Homiladorlikni baholashda\n"
            "- Tug‘ruqqa tayyorgarlikni nazorat qilishda",

"Vasopressin": "🔬 Vasopressin (Antidiuretik gormon, suv muvozanatini saqlovchi)\n"
                "➔ Norma:\n"
                "- 1 – 5 pg/mL\n\n"
                "📈 Oshganda:\n"
                "- Suvni saqlash va suvsizlanishdan himoya qilish\n"
                "- SIADH (antidiuretik gormon sekretsiyasining ortishi)\n\n"
                "📉 Kamayganda:\n"
                "- Diabet insipidus (suv tutib turolmaslik)\n"
                "- Suv yetishmovchiligi va ko‘p siydik chiqarish\n\n"
                "⚡ Organizmdagi belgilar:\n"
                "- Suvsizlanish\n"
                "- Tez-tez siydik chiqarish\n"
                "- Chanqoqning oshishi\n\n"
                "⏰ Qachon tekshirish kerak:\n"
                "- Suv va elektrolit muammolarida\n"
                "- Siydik chiqarish buzilishlarida",
"Adrenalin": "🔬 Adrenalin (Stress va kurashish gormoni)\n"
              "➔ Norma:\n"
              "- 0 – 140 pg/mL\n\n"
              "📈 Oshganda:\n"
              "- Stress, xavotir\n"
              "- Feoxromositoma (buyrak usti bezining o‘smasi)\n"
              "- Yurak-qon tomir kasalliklari\n\n"
              "📉 Kamayganda:\n"
              "- Buyrak usti bezining yetishmovchiligi\n"
              "- Og‘ir stressdan so‘ng organizmning charchashi\n\n"
              "⚡ Organizmdagi belgilar:\n"
              "- Yurak urishining tezlashishi\n"
              "- Qon bosimining oshishi\n"
              "- Bezovtalik va qo‘rquv hislari\n\n"
              "⏰ Qachon tekshirish kerak:\n"
              "- Stress va feoxromositoma shubhasida\n"
              "- Qon bosimi va yurak urishidagi o‘zgarishlarda",
              
"Noradrenalin": "🔬 Noradrenalin (Stress va qon bosimini tartibga soluvchi gormon)\n"
                 "➔ Norma:\n"
                 "- 70 – 750 pg/mL\n\n"
                 "📈 Oshganda:\n"
                 "- Stress va xavotir\n"
                 "- Feoxromositoma\n"
                 "- Yurak-qon tomir kasalliklari\n\n"
                 "📉 Kamayganda:\n"
                 "- Buyrak usti bezining faoliyati pasayishi\n"
                 "- Asab tizimi zaiflashishi\n\n"
                 "⚡ Organizmdagi belgilar:\n"
                 "- Qon bosimining pastligi\n"
                 "- Energiya yetishmovchiligi\n"
                 "- Charchoq va ruhiy tushkunlik\n\n"
                 "⏰ Qachon tekshirish kerak:\n"
                 "- Stress va asab tizimi buzilishlari shubhasida\n"
                 "- Feoxromositoma tashxisida",
                 
"Thyroglobulin": "🔬 Thyroglobulin (Qalqonsimon bezga oid marker)\n"
                  "➔ Norma:\n"
                  "- 1.4 – 78 ng/mL\n\n"
                  "📈 Oshganda:\n"
                  "- Qalqonsimon bez o‘smasi (differensial raklar)\n"
                  "- Qalqonsimon bezni yallig‘lanish kasalliklari\n\n"
                  "📉 Kamayganda:\n"
                  "- Qalqonsimon bez faoliyatining pastligi\n"
                  "- Qalqonsimon bezning jarrohlik yo‘li bilan olib tashlanishi\n\n"
                  "⚡ Organizmdagi belgilar:\n"
                  "- Qalqonsimon bezda shish yoki o‘sma\n"
                  "- Gormon disbalansi belgilari\n\n"
                  "⏰ Qachon tekshirish kerak:\n"
                  "- Qalqonsimon bez o‘sma va jarrohlikdan so‘ng nazoratda\n"
                  "- Qalqonsimon bez kasalliklarida",
                  
"Catecholamines": "🔬 Catecholamines (Adrenalin, Noradrenalin va Dopamin gormonlari majmuasi)\n"
                   "➔ Norma:\n"
                   "- 14 – 1100 pg/mL (turiga qarab)\n\n"
                   "📈 Oshganda:\n"
                   "- Feokromositoma\n"
                   "- Stress va xavotir\n"
                   "- Yurak-qon tomir tizimi kasalliklari\n\n"
                   "📉 Kamayganda:\n"
                   "- Buyrak usti bezining faoliyat pasayishi\n"
                   "- Asab tizimi zaiflashishi\n\n"
                   "⚡ Organizmdagi belgilar:\n"
                   "- Qon bosimining o‘zgarishi\n"
                   "- Yurak urishining tezlashishi yoki sekinlashishi\n"
                   "- Charchoq, energiya yetishmovchiligi\n\n"
                   "⏰ Qachon tekshirish kerak:\n"
                   "- Stress kasalliklarida\n"
                   "- Buyrak usti va yurak-qon tomir tizimini baholashda",
"Plazma_Metanefrin": "🔬 Plazma Metanefrin (Feoxromositoma va adrenal kasalliklarni aniqlash uchun test)\n"
                      "➔ Norma:\n"
                      "- < 90 pg/mL\n\n"
                      "📈 Oshganda:\n"
                      "- Feokromositoma\n"
                      "- Stress\n"
                      "- Qon bosimining oshishi\n\n"
                      "📉 Kamayganda:\n"
                      "- Normal holat\n\n"
                      "⚡ Organizmdagi belgilar:\n"
                      "- Yurak urishining tezlashishi\n"
                      "- Qon bosimining oshishi\n"
                      "- Bezovtalik va titroq\n\n"
                      "⏰ Qachon tekshirish kerak:\n"
                      "- Feokromositoma tashxisida\n"
                      "- Stressga aloqador kasalliklar shubhasida",

"Free_Metanefrin": "🔬 Free Metanefrin (Erkin Metanefrin, buyrak usti bezini tekshirish)\n"
                    "➔ Norma:\n"
                    "- < 57 pg/mL\n\n"
                    "📈 Oshganda:\n"
                    "- Feokromositoma\n"
                    "- Stressga kuchli javob\n\n"
                    "📉 Kamayganda:\n"
                    "- Normal holat\n\n"
                    "⚡ Organizmdagi belgilar:\n"
                    "- Qon bosimining oshishi\n"
                    "- Yurak urishining tezlashishi\n"
                    "- Bezovtalik, asabiylik\n\n"
                    "⏰ Qachon tekshirish kerak:\n"
                    "- Feokromositoma va adrenal kasalliklar shubhasida",

"Normetanefrin": "🔬 Normetanefrin (Noradrenalindan hosil bo‘ladigan metabolit)\n"
                  "➔ Norma:\n"
                  "- < 148 pg/mL\n\n"
                  "📈 Oshganda:\n"
                  "- Feokromositoma\n"
                  "- Stress va adrenal faoliyatning ortishi\n\n"
                  "📉 Kamayganda:\n"
                  "- Normal holat\n\n"
                  "⚡ Organizmdagi belgilar:\n"
                  "- Yurak urishining tezlashishi\n"
                  "- Qon bosimining o‘zgarishi\n"
                  "- Ruhiy bezovtalik\n\n"
                  "⏰ Qachon tekshirish kerak:\n"
                  "- Feokromositoma tashxisida\n"
                  "- Stress va adrenal buzilishlar baholashda",
}
